/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Animateria (https://sketchfab.com/Animateria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cybercity-2099-v2-3b61335c2a004a9ea31c8dab59471222
Title: CyberCity_2099_V2
*/
import React, { useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "react-three-fiber";
// import { useControls } from "leva";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

interface CustomNodes {
  [key: string]: {
    geometry: any; // Replace 'any' with the actual type of geometry
  };
}

interface SceneProps {
  scale: number;
  className?: string;
  // Define props here if your component accepts any
}

const Scene: React.FC<SceneProps> = (props) => {
  const { nodes, materials } = useGLTF("/scene.gltf") as unknown as {
    nodes: CustomNodes;
    materials: any;
  };

  const tl = gsap.timeline();
  const { camera, scene } = useThree();

  //----- used for getting the position for the shoes ----
  // const { cameraPosition, scenePosition, sceneRotation } = useControls({
  // 	cameraPosition: {
  // 		value: {
  // 			x: 6.05,
  // 			y: -0.80,
  // 			z: -4.35,
  // 		},
  // 		step: 0.05,
  // 	},
  // 	scenePosition: {
  // 		value: { x:   5.50, y: -1.55, z: -6.90 },
  // 		step: 0.05,
  // 	},

  // 	sceneRotation: {
  // 		value: { x: 0.08, y: -0.30, z: 0.03 },
  // 		step: 0.01,
  // 	},
  // });

  useLayoutEffect(() => {
    new ScrollTrigger({});
    // component About.tsx
    tl.to(camera.position, {
      x: 6.05,
      y: -0.8,
      z: -4.35,
      scrollTrigger: {
        trigger: ".second-section",
        start: "top bottom",
        end: "top top",
        scrub: true,
        immediateRender: false,
      },
    })
      .to(scene.position, {
        x: 5.5,
        y: -1.55,
        z: -6.9,
        scrollTrigger: {
          trigger: ".second-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })

      .to(scene.rotation, {
        x: 0.08,
        y: -0.3,
        z: 0.03,
        scrollTrigger: {
          trigger: ".second-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })

      // component - BuyNow.tsx
      .to(camera.position, {
        x: 3.2,
        y: -0.8,
        z: -6.55,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.position, {
        x: 3.2,
        y: -1.85,
        z: -8.0,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.rotation, {
        x: 0.17,
        y: -0.21,
        z: -0.01,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })

      .to(camera.position, {
        x: 6.05,
        y: -0.2,
        z: -6.6,
        scrollTrigger: {
          trigger: ".fourth-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.position, {
        x: 5.35,
        y: -1.55,
        z: -7.3,
        scrollTrigger: {
          trigger: ".fourth-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })

      .to(scene.rotation, {
        x: -0.02,
        y: -1.52,
        z: 0.0,
        scrollTrigger: {
          trigger: ".fourth-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      });
  }, []);

  // useFrame(() => {
  // 	camera.position.x = cameraPosition.x;
  // 	camera.position.y = cameraPosition.y;
  // 	camera.position.z = cameraPosition.z;
  // 	scene.position.x = scenePosition.x;
  // 	scene.position.y = scenePosition.y;
  // 	scene.position.z = scenePosition.z;
  // 	scene.rotation.x = sceneRotation.x;
  // 	scene.rotation.y = sceneRotation.y;
  // 	scene.rotation.z = sceneRotation.z;
  // });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Beacons_red_light_0.geometry}
          material={materials.red_light}
        />
        <mesh
          geometry={nodes.Beacons_beacons_base_0.geometry}
          material={materials.beacons_base}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Publicity_lights_Publicity_lights_0.geometry}
          material={materials.Publicity_lights}
        />
        <mesh
          geometry={nodes.Publicity_lights_Publicity_lights_outline_0.geometry}
          material={materials.Publicity_lights_outline}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Buildings_Windows_Windows_no_emit_0.geometry}
          material={materials.Windows_no_emit}
        />
        <mesh
          geometry={nodes.Buildings_Windows_Windows_ilum_B_0.geometry}
          material={materials.Windows_ilum_B}
        />
        <mesh
          geometry={nodes.Buildings_Windows_Windows_ilum_Y_0.geometry}
          material={materials.Windows_ilum_Y}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Trees_Terrain_Trees_Base_0.geometry}
          material={materials.Trees_Base}
        />
        <mesh
          geometry={nodes.Trees_Terrain_Trees_Base_0_1.geometry}
          material={materials.Trees_Base}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Publicity_lights_1_Publicity_lights_0.geometry}
          material={materials.Publicity_lights}
        />
        <mesh
          geometry={
            nodes.Publicity_lights_1_Publicity_lights_outline_0.geometry
          }
          material={materials.Publicity_lights_outline}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Lamp_Post_1_Lamp_Post_1_0.geometry}
          material={materials.Lamp_Post_1}
        />
        <mesh
          geometry={nodes.Lamp_Post_1_Blue_emit_0.geometry}
          material={materials.Blue_emit}
        />
      </group>
      <mesh
        geometry={nodes.Hovercars_Holograms_0.geometry}
        material={materials.Holograms}
        position={[33601.477, 10889.495, 25652.523]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Streets_outline_Streets_outline_0.geometry}
        material={materials.Streets_outline}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Solar_panel_Solar_panel_0.geometry}
        material={materials.Solar_panel}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Solar_panel_base_Solar_panel_base_0.geometry}
        material={materials.Solar_panel_base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_neon_orange_Publicity_neon_orange_0.geometry}
        material={materials.Publicity_neon_orange}
        position={[6814.926, 5723.899, 8157.469]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_neon_Buildings_neon_0.geometry}
        material={materials.Buildings_neon}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_1_top_Buildings_1_top_0.geometry}
        material={materials.Buildings_1_top}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Publicity_2D_Publicity_2D_0.geometry}
        material={materials.Publicity_2D}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Red_dish_Red_dish_0.geometry}
        material={materials.Red_dish}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_neon_green_Publicity_neon_green_0.geometry}
        material={materials.Publicity_neon_green}
        position={[-20305.059, 6960.812, 18946.486]}
        rotation={[-Math.PI / 2, 0, 2.356]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_neon_pink_Publicity_neon_pink_0.geometry}
        material={materials.Publicity_neon_pink}
        position={[17582.67, 5337.333, 9320.893]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_neon_blue_Publicity_neon_blue_0.geometry}
        material={materials.Publicity_neon_blue}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Trash_Trash_0.geometry}
        material={materials.Trash}
        position={[0, -76.992, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Terrain_Terrain_0.geometry}
        material={materials.Terrain}
        position={[-1063.896, 0, -161.555]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[10638.297, 10638.297, 100]}
      />
      <mesh
        geometry={nodes.Buildings_1_Buildings_1_0.geometry}
        material={materials.Buildings_1}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Buildings_0_Buildings_0_0.geometry}
        material={materials.Buildings_0}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Bridge_outline_Bridge_outline_0.geometry}
        material={materials.Bridge_outline}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Sidewalks_outline_Sidewalks_outline_0.geometry}
        material={materials.Sidewalks_outline}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Bridge_support_Bridge_support_0.geometry}
        material={materials.Bridge_support}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_adds_Buildings_adds_0.geometry}
        material={materials.Buildings_adds}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_0_1_Buildings_0_1_0.geometry}
        material={materials.Buildings_0_1}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Buildings_2_top_Buildings_2_top_0.geometry}
        material={materials.Buildings_2_top}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Terrain_base_Terrain_base_0.geometry}
        material={materials.Terrain_base}
        position={[-1063.896, 0, -161.555]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[10638.297, 10638.297, 100]}
      />
      <mesh
        geometry={nodes.Buildings_0_top_Buildings_0_top_0.geometry}
        material={materials.Buildings_0_top}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Sidewalks_Sidewalks_0.geometry}
        material={materials.Sidewalks}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Streets_Streets_0.geometry}
        material={materials.Streets}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Streets_2_Streets_2_0.geometry}
        material={materials.Streets_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Hyper_loop_Hyper_loop_0.geometry}
        material={materials.Hyper_loop}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_adds_top_Buildings_adds_top_0.geometry}
        material={materials.Buildings_adds_top}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_3_Buildings_3_0.geometry}
        material={materials.Buildings_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_neon_red_Publicity_neon_red_0.geometry}
        material={materials.Publicity_neon_red}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Trees_Base_Trees_Base_0.geometry}
        material={materials.Trees_Base}
        position={[724.151, -31.938, 33491.973]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Buildings_2_Buildings_2_0.geometry}
        material={materials.Buildings_2}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Alpha_mesh_Alpha_mesh_0.geometry}
        material={materials.Alpha_mesh}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Publicity_2D_1_Publicity_2D_0.geometry}
        material={materials.Publicity_2D}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Play_garden_Play_garden_0.geometry}
        material={materials.Play_garden}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Pool_Water_Pool_Water_0.geometry}
        material={materials.Pool_Water}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Bridge_base_Bridge_base_0.geometry}
        material={materials.Bridge_base}
        position={[-51323.469, 0, 339403.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={245360.688}
      />
      <mesh
        geometry={nodes.Lamp_post_lamppost_0.geometry}
        material={materials.lamppost}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
};
export default Scene;

// useGLTF.preload("/scene.gltf");
