/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: born2012 (https://sketchfab.com/born2012)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-city-1-14d2eaa145ee42938e004115871adf6c
Title: Cyberpunk City - #1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.449}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.015}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Meshpart1Mtl} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Meshpart2Mtl} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Meshpart3Mtl} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Meshpart4Mtl} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Meshpart5Mtl} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Meshpart6Mtl} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Meshpart7Mtl} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Meshpart8Mtl} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Meshpart9Mtl} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Meshpart11Mtl} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Meshpart12Mtl} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Meshpart13Mtl} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Meshpart14Mtl} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Meshpart15Mtl} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.Meshpart16Mtl} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Meshpart17Mtl} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Meshpart18Mtl} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.Meshpart19Mtl} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Meshpart20Mtl} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Meshpart21Mtl} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Meshpart22Mtl} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Meshpart23Mtl} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Meshpart24Mtl} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Meshpart26Mtl} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Meshpart27Mtl} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Meshpart28Mtl} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.Meshpart30Mtl} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.Meshpart32Mtl} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.Meshpart35Mtl} />
            <mesh geometry={nodes.Object_33.geometry} material={materials.Meshpart36Mtl} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
